/**
 * TaskMaster api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProcessEtat } from './processEtat';
import { ExitSignalType } from './exitSignalType';
import { RestartType } from './restartType';


export interface ListProcessInner { 
    id: number;
    name: string;
    nbInstance: number;
    startAtLaunch: boolean;
    restartType: RestartType;
    expectedExitCode: number;
    startupTime: number;
    restartRetryCount: number;
    exitSignal: ExitSignalType;
    gracefulStopTime: number;
    environement: object;
    umask: string;
    etat: ProcessEtat;
}
export namespace ListProcessInner {
}


