/**
 * TaskMaster api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnvValue } from './envValue';
import { ProcessEtat } from './processEtat';
import { ExitSignalType } from './exitSignalType';
import { RestartType } from './restartType';
import { ChildsProcess } from './childsProcess';


export interface Process { 
    name: string;
    nbInstance: number;
    childs?: Array<ChildsProcess>;
    startAtLaunch: boolean;
    restartType: RestartType;
    expectedExitCode: number;
    startupTime: number;
    restartRetryCount: number;
    exitSignal: ExitSignalType;
    gracefulStopTime: number;
    environement: Array<EnvValue>;
    umask: string;
    etat: ProcessEtat;
}
export namespace Process {
}


