patch:
  tags:
    - taskmaster
  operationId: updateConfig
  summary: Met a jour le fichier de configuration
  requestBody:
    description: Json file
    required: true
    content:
      application/json:
        schema:
          type: string
  responses:
    '200':
      description: 'ok'
