/**
 * TaskMaster api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Process } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface TaskmasterServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Renvois la liste des process
     * 
     */
    listProcess(extraHttpRequestParams?: any): Observable<Array<Process>>;

    /**
     * Redemarre un process
     * 
     * @param id 
     */
    restart(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Demarre un process
     * 
     * @param id 
     */
    start(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Arette un process
     * 
     * @param id 
     */
    stop(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Met a jour le fichier de configuration
     * 
     * @param body Json file
     */
    updateConfig(body: string, extraHttpRequestParams?: any): Observable<{}>;

}
