openapi: 3.0.0
info:
  title: TaskMaster api
  version: 1.0.0
servers:
  - url: http://localhost:8080/
paths:
  /start:
    summary: "Demarre un process"
    $ref: "./paths/start.yaml"
  /stop:
    summary: "Arrete un process"
    $ref: "./paths/stop.yaml"
  /restart:
    summary: "Redemare un process"
    $ref: "./paths/restart.yaml"
  /listGroupProcess:
    summary: "Retourne la liste des process"
    $ref: "./paths/listGroupProcess.yaml"
  /groupProcess:
    summary: "Renvois un groupe de process"
    $ref: "./paths/groupProcess.yaml"
  /processLog:
    summary: "Renvoi les logs d'un groupe de process"
    $ref: "./paths/processLog.yaml"
  /processLogError:
    summary: "Renvoi les logs d'Error d'un groupe de process"
    $ref: "./paths/processLogError.yaml"
  /deleteProcess:
    summary: "Delete un process"
    $ref: "./paths/deleteProcess.yaml"
  /editProcess:
    summary: "Edit un process"
    $ref: "./paths/editProcess.yaml"
  /createProcess:
    summary: "Ajoute un process"
    $ref: "./paths/createProcess.yaml"
