openapi: 3.0.0
info:
  title: TaskMaster api
  version: 1.0.0
servers:
  - url: http://localhost:8080/
paths:
  /start:
    summary: "Demarre un process"
    $ref: "./paths/start.yaml"
  /stop:
    summary: "Arrete un process"
    $ref: "./paths/stop.yaml"
  /restart:
    summary: "Redemare un process"
    $ref: "./paths/restart.yaml"
  /listGroupProcess:
    summary: "Retourne la liste des process"
    $ref: "./paths/listGroupProcess.yaml"
  /updateConfig:
    summary: "Met a jour le fichier de configuration"
    $ref: "./paths/updateConfig.yaml"
  /groupProcess:
    summary: "Renvois un groupe de process"
    $ref: "./paths/groupProcess.yaml"
